DROP TABLE IF EXISTS users;

CREATE TABLE users(
id SERIAL PRIMARY KEY,
firstname VARCHAR (100) NOT NULL,
lastname VARCHAR (100) NOT NULL,
email VARCHAR (150) NOT NULL UNIQUE,
password VARCHAR (100) NOT NULL,
bio VARCHAR (300),
users_image VARCHAR (450),
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
