DROP TABLE IF EXISTS users;

CREATE TABLE users(
id SERIAL PRIMARY KEY,
firstname VARCHAR (100) NOT NULL,
lastname VARCHAR (100) NOT NULL,
email VARCHAR (150) NOT NULL,
password VARCHAR (100) NOT NULL,
bio VARCHAR (300) NOT NULL,
users_image VARCHAR (450) NOT NULL,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
